### ISSUE TITLE
GSoC 

### ISSUE THREAD

**Issue by nileshchat** [iiitv/workshops#5]
@aviaryan This year's experiance along with tips to gets started with preparation for GSoC 2017

**Comment by yashLadha** [comment]
Gsoc is round the corner. This workshop should held early. For 2 year and 3 year

**Comment by ShalineeSingh** [comment]
I'll suggest you to include the first year guys too. At least they will know what GSoC is and how things take place.

**Comment by aviaryan** [comment]
Workshop conducted on 3rd Feb, 2017.
