### ISSUE TITLE
Code Ground

### ISSUE THREAD

**Issue by yashLadha** [iiitv/workshops#6]
To do more from less line of code

**Comment by aviaryan** [comment]
Can you please clarify more on what do you mean by "Code Ground" ? Links would be helpful.

**Comment by yashLadha** [comment]
my idea is to encourage others to solve a problem in minimum no. of lines of code like a single line statement. In functional programming paradigm we can perform these types of task with ease. http://blog.hackerrank.com/fizzbuzz/ . this can be taken as a weekly event to do
